### ISSUE TITLE
Add Open Source For You as National Media Partner

### ISSUE THREAD

**Issue by bmsantosh** [Qwinix/gopherconindia.github.io#436]
Brief: Launched in January 2003, Open Source For You is a complete magazine on open source, and is today a big hit with those who love FOSS (Free and Open Source Software). The magazine carries tech articles on Linux and open source for newbies, administrators, developers and fans of open source. Its main objective, however, is to help organisations enhance their return on investment (RoI) by deploying open source solutions.

URL: http://www.opensourceforu.com/

Logo: mailed

Checklist:

1. Add logo under supporters at home page
2. Add a new section called "National Media" after "International Media" with logo and brief at http://www.gophercon.in/supporters/
3. Add at http://www.gophercon.in/talk-schedule/

**Comment by leehas** [comment]
Updated:

http://qwinix.github.io/gopherconindia.github.io/supporters/
