### ISSUE TITLE
Add Prasad Krishnan to Go Workshop page

### ISSUE THREAD

**Issue by bmsantosh** [Qwinix/gopherconindia.github.io#451]
*Add Prasad Krishnan to Go Workshop page

Twitter Handle : @maskoniya
Github: https://github.com/prasus

Image: https://cloud.githubusercontent.com/assets/1052069/5715396/48b80868-9afe-11e4-8dcc-2cb34c405dd6.jpg

**Comment by leehas** [comment]
updated:
http://qwinix.github.io/gopherconindia.github.io/go-workshop/
