### ISSUE TITLE
Add CodeIgnition as a Silver Sponsor

### ISSUE THREAD

**Issue by bmsantosh** [Qwinix/gopherconindia.github.io#457]
*Add CodeIgnition as a Silver Sponsor

Brief: 
CodeIgnition is a start-up that provides business solutions using DevOps, infrastructure automation, cloud, virtualization and mobile & business apps. We help new & emerging start-ups to build, deploy, automate & scale performance-critical solutions.

Logo: mailed

**Comment by leehas** [comment]
Updated:
http://qwinix.github.io/gopherconindia.github.io/#sponsor
