### ISSUE TITLE
Change Qwinix Workshop participants

### ISSUE THREAD

**Issue by bmsantosh** [Qwinix/gopherconindia.github.io#472]
*Replace Mathew Joseph with Kedarnag M Satish in alphabetical order. 

GitHub: https://github.com/Kedarnag13
Twitter: NA

Photo: kindly receive the same from Raghu

**Comment by leehas** [comment]
Twiiter link ?

**Comment by bmsantosh** [comment]
No Twitter link for now. We can update it later.

**Comment by leehas** [comment]
Updated:
http://qwinix.github.io/gopherconindia.github.io/go-workshop/
