### ISSUE TITLE
Add Real Image Media Technologies Pvt Ltd. as Gold Sponsor

### ISSUE THREAD

**Issue by bmsantosh** [Qwinix/gopherconindia.github.io#477]
Brief: 
Justickets [www.justickets.in] is a cool new movie ticketing website for the Indian market and an associate company of global entertainment technology pioneer, Qube Cinema. A comprehensive end-to-end digital cinema platform with products for mastering, distributing and playing movies, Qube Cinema has an installed base in 48 countries and is the largest digital cinema network in India with powerful satellite-connected on-screen advertising. Qube Cinema is a subsidiary of Real Image Media Technologies – the company that was instrumental in dramatically changing India’s entertainment industry, not just once but three times, bringing about paradigm creative shifts in production, post-production and exhibition using the power of technology. After impacting how movies are made and exhibited locally and internationally over the last three decades, the company built MovieBuff and CinemaDB to provide modern, clean, snappy websites with programmatic access to the most accurate movie, talent and cinema information, thus enabling an enhanced movie ticketing experience with Justickets. Built with Go, Justickets is the first consumer-facing tool that showcases the company's extensive cinema experience and footprint by offering a quick and easy way to book tickets online for current and upcoming movie releases across a growing base of Indian cities and towns.

Logo: link to www.justickets.in
![justickets-logo 1](https://cloud.githubusercontent.com/assets/7664752/5914667/c8a527fa-a61f-11e4-9496-8386c6cde684.jpg)

**Comment by leehas** [comment]
Lets do this once we get the complete description

**Comment by bmsantosh** [comment]
@leehas: This needs to be updated for now as mentioned.

**Comment by leehas** [comment]
Updated:
http://qwinix.github.io/gopherconindia.github.io/

**Comment by leehas** [comment]
Updated:
http://qwinix.github.io/gopherconindia.github.io/
