### ISSUE TITLE
Add Saravana Kumar to Go Workshop

### ISSUE THREAD

**Issue by bmsantosh** [Qwinix/gopherconindia.github.io#489]
*Add Saravana Kumar to Go Workshop

Image:
![saravana](https://cloud.githubusercontent.com/assets/7664752/5971141/411386fe-a865-11e4-921b-7066c4e2ecda.jpg)

No Twitter and GitHub

**Comment by leehas** [comment]
Updated:
http://qwinix.github.io/gopherconindia.github.io/go-workshop/
