### ISSUE TITLE
Add 2 people to the Go Workshop

### ISSUE THREAD

**Issue by bmsantosh** [Qwinix/gopherconindia.github.io#501]
* Add 2 people to the Go Workshop

1) Basil Kurian
Image: https://media.licdn.com/mpr/mpr/shrinknp_200_200/p/2/005/0ad/2ae/3b08374.jpg
GitHub: https://github.com/bkurian
Twitter: no

2) Binish A R
Image: https://media.licdn.com/mpr/mpr/shrink_400_400/p/5/000/20b/14a/0d02d20.jpg
GitHub: https://github.com/arbinish
Twitter: no

**Comment by leehas** [comment]
Updated:
http://qwinix.github.io/gopherconindia.github.io/go-workshop/
